### ISSUE TITLE
Overall looks good, needs some style!

### ISSUE THREAD

**Issue by soggybag** [jayceazua/tipCalc#1]
https://github.com/jayceazua/tipCalc/blob/b69d7fbf533c25710de1aede87c9d656139f6c55/index.html#L1

This looks good and is working well. It needs some styles! Even just a few styles would go a long way to making it look great.

**Comment by jayceazua** [comment]
Hey Mitch! finished that right after! Thank you still need a good over view of CSS (grid, flex, and css) how to go about styling...
